version: '3.7'
services:
  java-srv:
    build: java-srv
    ports:
      - 80:9000
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      - MSSQL_SA_PASSWORD=z!oBx1ab
      - ACCEPT_EULA=Y
    ports:
      - 1433
    healthcheck:
      test: "pwd"